export interface HardTopic {
  id: string;
  icon: string;
  title: string;
  whyHard: string;
  approach: string;
  keyPoints: string[];
  example: string;
  bucket?: "razonamiento" | "cálculo" | "imagen" | "urgencias";
}

export const hardTopics: HardTopic[] = [
  {
    id: "hard-bioestadistica",
    icon: "📐",
    title: "Bioestadística: OR, RR, RAR y NNT",
    whyHard: "Mezcla fórmulas, interpretación clínica y diseño de estudio.",
    approach: "Primero identifica el tipo de estudio. Casos-controles → OR. Cohortes/ensayos → RR. Luego traduce el resultado a lenguaje clínico.",
    keyPoints: [
      "OR en casos-controles.",
      "RR en cohortes y ensayos.",
      "RAR = riesgo control − riesgo experimental.",
      "NNT = 1/RAR.",
      "Si el IC incluye 1, no hay significación para RR/OR.",
    ],
    example: "Reducir un riesgo del 20% al 10% → RAR 10% → NNT 10.",
    bucket: "cálculo",
  },
  {
    id: "hard-pruebas",
    icon: "🔬",
    title: "Pruebas diagnósticas",
    whyHard: "Porque sensibilidad, especificidad y valores predictivos se confunden con facilidad.",
    approach: "Haz una tabla 2×2 mental y decide si la pregunta es de cribado, confirmación o prevalencia.",
    keyPoints: [
      "Cribado: sensibilidad alta.",
      "Confirmación: especificidad alta.",
      "VPP/VPN dependen de prevalencia.",
      "LR+ y LR− ayudan más que VPP/VPN en comparaciones.",
    ],
    example: "En baja prevalencia, aunque una prueba sea buena, el VPP puede ser bajo.",
    bucket: "razonamiento",
  },
  {
    id: "hard-cribado",
    icon: "🩻",
    title: "Cribado poblacional y salud pública",
    whyHard: "Hay que combinar epidemiología, coste-beneficio y sesgos.",
    approach: "Aplica Wilson-Jungner: enfermedad relevante, fase presintomática, prueba válida y tratamiento precoz útil.",
    keyPoints: [
      "Sesgo de adelanto diagnóstico.",
      "Sesgo de duración.",
      "Selección de sanos.",
      "No todo lo detectable merece cribado.",
    ],
    example: "Cribado de cáncer colorrectal sí; de enfermedad rara sin tratamiento eficaz, no.",
    bucket: "razonamiento",
  },
  {
    id: "hard-farmacologia",
    icon: "💊",
    title: "Farmacología clínica e interacciones",
    whyHard: "Porque las respuestas dependen de comorbilidades, embarazo, riñón e interacciones.",
    approach: "Piensa por familias y recuerda una contraindicación estrella por cada una.",
    keyPoints: [
      "Warfarina: teratógena, interacciones múltiples.",
      "IECA/ARA-II: embarazo y estenosis bilateral de renal.",
      "Aminoglucósidos: nefro y ototoxicidad.",
      "Clozapina: agranulocitosis.",
    ],
    example: "En gestante con trombosis, HBPM; nunca warfarina.",
    bucket: "razonamiento",
  },
  {
    id: "hard-gestante",
    icon: "🤰",
    title: "Manejo clínico en el embarazo",
    whyHard: "Porque cambia la seguridad de fármacos, pruebas y prioridades clínicas.",
    approach: "Clasifica por trimestre, detecta urgencias obstétricas y elige la opción segura para madre y feto.",
    keyPoints: [
      "Preeclampsia grave: sulfato de magnesio + finalizar gestación.",
      "HBPM en trombosis.",
      "Evitar tetraciclinas, warfarina e IECA.",
    ],
    example: "Amenorrea + dolor + sangrado = descartar ectópico primero.",
    bucket: "urgencias",
  },
  {
    id: "hard-scores",
    icon: "🔢",
    title: "Escalas y puntos de corte",
    whyHard: "Un solo punto cambia una decisión clínica.",
    approach: "Memoriza el acrónimo y el umbral clave para ingreso, anticoagulación o gravedad.",
    keyPoints: [
      "CURB-65 ≥2 → ingreso.",
      "CHA₂DS₂-VASc alto → anticoagulación.",
      "Wells guía siguiente prueba.",
      "NIHSS orienta gravedad.",
    ],
    example: "Neumonía con CURB-65 de 2 → ingreso hospitalario.",
    bucket: "razonamiento",
  },
  {
    id: "hard-imagen",
    icon: "🖼️",
    title: "Preguntas con imagen clínica",
    whyHard: "Combinan interpretación visual y presión de tiempo.",
    approach: "Lee primero el enunciado, identifica el hallazgo principal y después integra con la clínica.",
    keyPoints: [
      "ECG: ritmo, frecuencia, ST, QRS.",
      "Rx tórax: consolidación, derrame, neumotórax.",
      "TAC craneal: sangre vs isquemia.",
      "Dermato: ABCDE.",
    ],
    example: "ST elevado en derivaciones contiguas + dolor → IAMCEST aunque la imagen sea simple.",
    bucket: "imagen",
  },
  {
    id: "hard-urgencias",
    icon: "🚑",
    title: "Urgencias tiempo-dependientes",
    whyHard: "La dificultad no es el diagnóstico, sino elegir el orden correcto de actuación.",
    approach: "Piensa en ABCDE y en ventanas terapéuticas.",
    keyPoints: [
      "Ictus: TAC y trombólisis <4,5 h.",
      "IAMCEST: reperfusión precoz.",
      "Meningitis: antibiótico precoz.",
      "Shock séptico: líquidos + noradrenalina si precisa.",
    ],
    example: "En ictus, primero descartar hemorragia; no anticoagules a ciegas.",
    bucket: "urgencias",
  },
  {
    id: "hard-neonato",
    icon: "👶",
    title: "Neonatología de alto rendimiento",
    whyHard: "Los valores normales, prioridades y diagnósticos cambian respecto al adulto.",
    approach: "Pregunta clave: ¿esto en un recién nacido es fisiológico o patológico?",
    keyPoints: [
      "Ictericia en primeras 24 h = patológica.",
      "Apgar no decide reanimación por sí solo.",
      "Bronquiolitis: soporte, no antibiótico rutinario.",
    ],
    example: "Ictericia a las 12 h de vida → pensar en hemólisis, no en ictericia fisiológica.",
    bucket: "urgencias",
  },
  {
    id: "hard-hemato",
    icon: "🩸",
    title: "Anemias y microcitosis",
    whyHard: "Las preguntas juegan con perfiles analíticos parecidos.",
    approach: "Mira primero VCM y ferritina. Luego TIBC y saturación de transferrina.",
    keyPoints: [
      "Ferropenia: ferritina baja, TIBC alta.",
      "Inflamación crónica: ferritina normal/alta, TIBC baja.",
      "Talasemia: microcitosis con ferritina normal.",
    ],
    example: "Varón con ferropenia = descartar sangrado digestivo hasta demostrar lo contrario.",
    bucket: "razonamiento",
  },
  {
    id: "hard-renal",
    icon: "🧂",
    title: "Trastornos hidroelectrolíticos",
    whyHard: "Requieren fisiología, números y priorización terapéutica.",
    approach: "Antes de pensar en la causa, identifica qué mata primero: potasio, sodio o acidosis grave.",
    keyPoints: [
      "Hiperpotasemia grave: calcio IV, insulina + glucosa, medidas de eliminación.",
      "Hiponatremia: corregir despacio para evitar mielinólisis.",
      "Acidosis severa puede requerir diálisis si hay contexto renal.",
    ],
    example: "LRA con K 7,2 y ECG alterado → tratar potasio antes de ampliar estudio.",
    bucket: "urgencias",
  },
  {
    id: "hard-psiquiatria",
    icon: "🧩",
    title: "Psiquiatría diferencial",
    whyHard: "Varias entidades comparten síntomas, pero cambian por duración y relación con estado de ánimo.",
    approach: "Pregunta por duración, deterioro funcional y si la psicosis existe fuera de episodios afectivos.",
    keyPoints: [
      "Esquizofrenia: >6 meses.",
      "Esquizoafectivo: psicosis + episodios afectivos, con psicosis aislada alguna vez.",
      "Depresión psicótica: la psicosis ocurre dentro del episodio depresivo.",
    ],
    example: "Si hay síntomas psicóticos persistentes fuera de la depresión, no es solo depresión psicótica.",
    bucket: "razonamiento",
  },
  {
    id: "hard-gasometria",
    icon: "🧪",
    title: "Gasometría y Trastornos Ácido-Base Mixtos",
    whyHard: "Requiere seguir algoritmos secuenciales de pH, pCO₂ y HCO₃⁻, calculando Anion Gap.",
    approach: "1º Mira pH (acidemia/alcalemia). 2º Mira quién es el primario (pCO₂ o HCO₃⁻). 3º Calcula el Anion Gap = Na − (Cl + HCO₃). 4º Comprueba compensación esperada.",
    keyPoints: [
      "Anion Gap normal (8-12): Diarrea, acidosis tubular renal.",
      "Anion Gap elevado (>12): Cetoacidosis, Acidosis láctica, Uremia, Tóxicos (Metanol/Etilenglicol).",
      "Si la pCO₂ no compensa exactamente lo previsto, hay un segundo trastorno respiratorio superpuesto.",
    ],
    example: "pH 7.18, pCO₂ 25, HCO₃ 9, Na 140, Cl 100 → Acidosis metabólica con Anion Gap alto (31) e hiperventilación compensatoria.",
    bucket: "cálculo",
  },
  {
    id: "hard-arritmias-qrs",
    icon: "⚡",
    title: "Taquicardias de QRS Ancho y Canalopatías",
    whyHard: "Diferenciar Taquicardia Ventricular de TVSP con aberrancia y reconocer patología eléctrica primaria.",
    approach: "Ante QRS ancho (>0.12s) e inestabilidad hemodinámica → Cardioversión eléctrica sin dudar. Si es estable, buscar criterios de Brugada/Vereckei.",
    keyPoints: [
      "QRS ancho en urgencias = Taquicardia Ventricular hasta demostrar lo contrario (85-90% de casos).",
      "Síndrome de Brugada: Elevación del ST tipo cóncavo/tienda en V1-V2.",
      "Síndrome de Wolff-Parkinson-White: PR corto (<0.12s) + Onda delta.",
      "QT largo congénito/adquirido: Riesgo de Torsade de Pointes (tratar con Sulfato de Magnesio).",
    ],
    example: "Paciente con antecedente de cardiopatía isquémica + Taquicardia QRS ancho → tratar como TV, NUNCA dar verapamilo.",
    bucket: "urgencias",
  },
  {
    id: "hard-glomerulonefritis",
    icon: "🩸",
    title: "Diagnóstico Diferencial de Glomerulonefritis",
    whyHard: "Múltiples síndromes histológicos con complementos (C3/C4) y anticuerpos que se solapan.",
    approach: "Clasifica por clínica (Nefrótico vs Nefrítico) y luego por niveles de complemento plasmático (C3/C4 bajo vs normal).",
    keyPoints: [
      "C3 e hipercomplementemia consumida: Postestreptocócica, Membranoproliferativa, Lupus (C3 y C4 bajos).",
      "Complemento NORMAL: Nefropatía IgA (Berger), Cambios Mínimos, Geometría Focal y Segmentaria, Membranosa.",
      "Nefrótico puro en adultos: Glomerulopatía Membranosa (anti-PLA2R+). En niños: Cambios Mínimos.",
    ],
    example: "Varón de 50 años con proteinuria nefrótica masiva y anti-PLA2R positivo → Nefritis Membranosa.",
    bucket: "razonamiento",
  },
  {
    id: "hard-lcr",
    icon: "💉",
    title: "Análisis Diagnóstico del LCR en Meningitis",
    whyHard: "Interpretar células, proteínas y glucosa en punción lumbar urgente para guiar antibioterapia.",
    approach: "Calcula el cociente Glucosa LCR / Glucosa Suero (<0.4 es patológico). Mira el predominio leucocitario (PMN vs Linfocitos).",
    keyPoints: [
      "Bacteriana aguda: PMN elevados (>1000), Glucosa MUY baja (<40% del suero), Proteínas muy altas (>100 mg/dL).",
      "Vírica: Linfocitos, Glucosa NORMAL (>60%), Proteínas ligeramente elevadas.",
      "Tuberculosa / Fúngica: Linfocitos, Glucosa MUY baja, Proteínas extremadamente altas.",
    ],
    example: "LCR turbio con 3.000 células (90% PMN), glucosa 15 mg/dL y proteínas 250 mg/dL → Meningitis Bacteriana.",
    bucket: "urgencias",
  },
  {
    id: "hard-ica-algoritmo",
    icon: "🧭",
    title: "Algoritmo de la insuficiencia cardíaca aguda",
    whyHard: "Secuencia diagnóstica y terapéutica de la ICA con edema pulmonar, clasificando por perfil hemodinámico (húmedo/seco, frío/caliente).",
    approach: "Clasifica la ICA en caliente/frío × húmedo/seco: el 'caliente y húmedo' responde a vasodilatadores + diurético + CPAP. El 'frío y húmedo' suma inotrópicos.",
    keyPoints: [
      "Determina si hay inestabilidad respiratoria/hemodinámica.",
      "El paciente está 'caliente y húmedo' (buena perfusión, congestión) → manejo con CPAP, nitratos IV y furosemida.",
      "La dobutamina se reserva para perfil 'frío'. La intubación es de rescate si falla la CPAP.",
    ],
    example: "Paciente con edema agudo de pulmón, PaO2 55 mmHg, con buena perfusión periférica. ¿Cuál es el manejo inmediato de elección?\n\nOpciones:\nA) Ventilación no invasiva (CPAP) + nitratos + diurético\nB) Intubación inmediata + adrenalina\nC) Dobutamina como único tratamiento\nD) Trombolisis\nE) Hemorragia punzante en blanco\n\nRespuesta correcta: A. Ventilación no invasiva (CPAP) + nitratos + diurético. En el edema agudo de pulmón con buen gasto, la ventilación no invasiva con presión positiva (CPAP/BiPAP) junto a nitratos y diurético es el pilar; evita la intubación en muchos casos.",
    bucket: "urgencias",
  },
  {
    id: "hard-gasometria-buffer",
    icon: "🧮",
    title: "Interpretación de gases: buffer vs compensación",
    whyHard: "Distinguir acidosis/alcalosis respiratoria vs metabólica y valorar compensación, un clásico buscado a intervalos regulares.",
    approach: "Usa pH→primario, luego mira el parámetro que 'empuja' el pH en cada acidosis/alcalosis, y por último comprueba si el HCO3 compensa dentro del rango agudo (1:10) o crónico (4:10).",
    keyPoints: [
      "pH bajo → acidosis.",
      "La PaCO2 alta → componente respiratorio.",
      "Para acidosis respiratoria aguda la compensación renal esperada: HCO3 aumenta ~1 mEq/L por cada 10 mmHg de PaCO2 por encima de 40 (crónica +4). HCO3 de 26 es prácticamente normal → aguda sin compensación.",
    ],
    example: "Gasometría: pH 7,28; PaCO2 55 mmHg; HCO3 26 mEq/L. El diagnóstico es:\n\nOpciones:\nA) Acidosis respiratoria aguda sin compensación renal\nB) Acidosis metabólica compensada\nC) Alcalosis respiratoria crónica\nD) Acidosis mixta respiratoria y metabólica\nE) Alcalosis metabólica\n\nRespuesta correcta: A. Acidosis respiratoria aguda sin compensación renal. Acidosis respiratoria aguda: pH ácido con PaCO2 elevada y HCO3 superior a lo normal apenas compensando.",
    bucket: "cálculo",
  },
  {
    id: "hard-ecg-bloqueos",
    icon: "🖼️",
    title: "Razón del ECG: bloques cardiacos",
    whyHard: "Distinguir Mobitz I, Mobitz II y bloqueo AV completo sobre una traza; pregunta de imagen repetida.",
    approach: "La palabra clave es 'progresivo'. Wenckebach = progresivo. Mobitz II = constante y abre la puerta a marcapasos.",
    keyPoints: [
      "Mira si TODAS las ondas P conducen a QRS.",
      "Si hay ondas P sin QRS → bloqueo de 2º.",
      "Observa el PR previo: si se alarga de forma progresiva → Mobitz I.",
      "Si el PR es constante y una P queda 'abortada' → Mobitz II.",
    ],
    example: "En un ECG con PR que se alarga progresivamente hasta perder una onda QRS en cada ciclo, el diagnóstico es:\n\nOpciones:\nA) Bloqueo AV 2º grado Mobitz I (Wenckebach)\nB) Bloqueo AV 2º grado Mobitz II\nC) Bloqueo AV de 1er grado\nD) Bloqueo AV completo\nE) Taquicardia ventricular\n\nRespuesta correcta: A. Bloqueo AV 2º grado Mobitz I (Wenckebach). PR se alarga progresivamente hasta que una onda P no se conduce, con RR decreciente.",
    bucket: "imagen",
  },
  {
    id: "hard-creatinina-dosis",
    icon: "🧮",
    title: "Cálculo del creatinina aclaramiento y dosificación",
    whyHard: "Ajuste de dosis según filtrado glomerular (Cockcroft-Gault), pregunta de cálculo frecuente.",
    approach: "Domina Cockcroft-Gault: [(140-edad)×peso]/(72×Cr), ×0,85 si mujer. Detecta la IRC para ajustar dosis renales. Practica muchos casos hasta automatizarlo.",
    keyPoints: [
      "Cockcroft-Gault: ClCr = [(140−edad) × peso] / (72 × Cr).",
      "Ejemplo: [(140−80)=60] × 70 = 4200; 72 × 1,5 = 108; 4200/108 ≈ 39 ml/min (varón).",
      "Ajustando, ~25-40 ml/min. La opción baja/límite de IRC es la correcta.",
    ],
    example: "Varón de 70 kg, 80 años, creatinina 1,5 mg/dL. Calcular el aclaramiento de creatinina estimado (aprox.) para decidir dosificación.\n\nOpciones:\nA) ~25 ml/min\nB) ~50 ml/min\nC) ~90 ml/min\nD) ~120 ml/min\nE) No se puede calcular\n\nRespuesta correcta: A. ~25 ml/min (Aproximadamente 39 ml/min en varón, en rango de IRC estadio 3; en mujer se multiplica por 0,85 para obtener ~33).",
    bucket: "cálculo",
  },
  {
    id: "hard-rx-torax",
    icon: "🖼️",
    title: "Imagen de radiografía torácica: derrame vs neumonía",
    whyHard: "Reconocer patrones radiológicos y el examen pregunta con una radiografía acompañada.",
    approach: "Menisco=derrame; broncograma aéreo=condensación; hiperclaridad sin trama=neumotórax; desplazamiento de mediastino hacia el lado=atelectasia.",
    keyPoints: [
      "El signo del menisco (línea cóncava) y borramiento del seno costofrénico dirigen a líquido libre = derrame.",
      "La neumonía da broncograma aéreo; el neumotórax da hiperclaridad sin vasos; la atelectasia desplaza estructuras hacia sí misma.",
    ],
    example: "Radiografía de tórax con velamiento de la base derecha con menisco y borramiento del seno costofrénico. Diagnóstico:\n\nOpciones:\nA) Derrame pleural\nB) Neumonía lobar derecha\nC) Atelectasia\nD) Neumotórax\nE) Masividad cardiaca\n\nRespuesta correcta: A. Derrame pleural. Opacidad de base con menisco ascendente y pérdida del seno costofrénico.",
    bucket: "imagen",
  },
  {
    id: "hard-hpylori-terapia",
    icon: "🧩",
    title: "Razonamiento de la prescripción final: H pylori",
    whyHard: "Elegir el esquema erradicador correcto según contexto de resistencias, un patrón de razonamiento clínico de alta frecuencia.",
    approach: "Pregunta siempre '¿qué dice el enunciado sobre resistencias?'. Alta resistencia a claritromicina → cuádruple con bismuto. El contexto de la pregunta dirige el tratamiento.",
    keyPoints: [
      "Identifica el perfil de resistencia local (dato clave del enunciado).",
      "Si la resistencia a claritromicina es alta, la triple estándar pierde eficacia.",
      "Se opta por la cuádruple con bismuto (2ª línea clásica / 1ª en zonas de riesgo).",
    ],
    example: "Zona residente con alta resistencia a claritromicina. Paciente con úlcera duodenal por H. pylori. Esquema de elección:\n\nOpciones:\nA) Cuádruple terapia con bismuto (IBP+bismuto+tetraciclina+metronidazol)\nB) Triple terapia estándar (IBP+claritromicina+amoxicilina)\nC) IBP en monoterapia\nD) Doble terapia con bismuto\nE) Metronidazol en monoterapia\n\nRespuesta correcta: A. Cuádruple terapia con bismuto (IBP+bismuto+tetraciclina+metronidazol) durante 14 días.",
    bucket: "razonamiento",
  },
];
