export interface TrapPattern {
  id: string;
  icon: string;
  title: string;
  pattern: string;
  trap: string;
  howToAvoid: string;
  example: string;
  level?: "básica" | "media" | "alta";
}

export const trapPatterns: TrapPattern[] = [
  {
    id: "trap-absolutos",
    icon: "🚫",
    title: "Respuestas absolutas (siempre, nunca, solamente)",
    pattern: "Una opción contiene palabras absolutas como «siempre», «nunca», «solamente», «en todos los casos».",
    trap: "En medicina casi nada es absoluto. Las opciones con absolutismos suelen ser la respuesta incorrecta.",
    howToAvoid: "Desconfía de los enunciados absolutos. Busca la palabra que invalida toda la opción; suele bastar un único ejemplo contrario para descartarla.",
    example: "«La amiodarona NUNCA produce toxicidad pulmonar» → falso: puede producir neumonitis intersticial.",
    level: "básica",
  },
  {
    id: "trap-excepto",
    icon: "🔄",
    title: "Preguntas inversas: «cuál NO» / «excepto» / «falso»",
    pattern: "El enunciado pide identificar la opción INCORRECTA o lo que NO corresponde, invirtiendo la lógica habitual.",
    trap: "El cerebro busca la respuesta verdadera por inercia y marca una opción correcta que, en esa pregunta, sería errónea.",
    howToAvoid: "Subraya la negación antes de leer opciones. Marca mentalmente las verdaderas y elige la que no encaja.",
    example: "«¿Cuál NO es criterio CURB-65?» CURB-65 = Confusión, Urea, FR, TA, edad ≥65. La fiebre no pertenece.",
    level: "básica",
  },
  {
    id: "trap-clave-tardia",
    icon: "👀",
    title: "Palabra clave al final del enunciado",
    pattern: "El verdadero objetivo aparece al final: «…en el embarazo», «…como primera medida», «…más específico».",
    trap: "Si respondes por intuición sin leer el final, marcas una respuesta general pero no la correcta para ese contexto.",
    howToAvoid: "Lee el enunciado entero y localiza el verbo clínico: diagnosticar, confirmar, tratar, derivar o estabilizar.",
    example: "No es lo mismo «mejor prueba diagnóstica» que «primera prueba a realizar». En TEP: angio-TAC confirma; Dímero-D se usa antes si la probabilidad es baja/intermedia.",
    level: "media",
  },
  {
    id: "trap-poblacion",
    icon: "🤰",
    title: "El cambio de población cambia la respuesta",
    pattern: "La respuesta correcta para un adulto puede ser falsa en gestantes, niños, ancianos o inmunodeprimidos.",
    trap: "Se responde con la pauta estándar sin notar una población especial.",
    howToAvoid: "Detecta edad, embarazo e inmunosupresión antes de mirar opciones. Eso cambia antibióticos, pruebas y urgencias.",
    example: "Anticoagulación en gestante → HBPM, no warfarina.",
    level: "media",
  },
  {
    id: "trap-sens-esp",
    icon: "🎯",
    title: "Sensibilidad vs. especificidad y valores predictivos",
    pattern: "Confunden lo que mide cada parámetro y olvidan que el VPP/VPN dependen de la prevalencia.",
    trap: "Se marca «alta sensibilidad = alto valor predictivo positivo» y eso no es cierto en poblaciones de baja prevalencia.",
    howToAvoid: "Cribado → sensibilidad. Confirmación → especificidad. VPP/VPN cambian con prevalencia.",
    example: "Una prueba muy sensible puede tener mal VPP si la enfermedad es rara.",
    level: "alta",
  },
  {
    id: "trap-nombres-similares",
    icon: "💊",
    title: "Fármacos y síndromes de nombre parecido",
    pattern: "Las opciones parecen muy similares, pero cambian por generación, espectro o indicación.",
    trap: "Se responde por parecido fonético, no por razonamiento farmacológico o sindrómico.",
    howToAvoid: "Asocia cada nombre con familia, indicación estrella y principal contraindicación.",
    example: "Cefazolina ≠ cefalexina ≠ ceftazidima.",
    level: "media",
  },
  {
    id: "trap-distractor-casi",
    icon: "🎭",
    title: "El distractor «casi correcto»",
    pattern: "Una opción es verdadera salvo por un detalle pequeño: dosis, tiempo, contraindicación, vía o población.",
    trap: "Parece impecable, pero contiene una condición falsa escondida.",
    howToAvoid: "Compara las dos opciones más plausibles y busca el detalle que las diferencia.",
    example: "«La fibrinólisis está indicada siempre que haya elevación del ST» → falso por contraindicaciones absolutas.",
    level: "alta",
  },
  {
    id: "trap-penalizacion",
    icon: "➖",
    title: "La trampa de la penalización",
    pattern: "Contestar al azar cuando no se puede descartar nada penaliza el resultado global.",
    trap: "Muchos candidatos sobrecontestan y pierden puntos netos.",
    howToAvoid: "Si no descartas ninguna, mejor blanco. Si descartas una o dos, el valor esperado mejora y suele compensar responder.",
    example: "Entre 2 opciones, contestar suele compensar; entre 4 al azar, no.",
    level: "básica",
  },
  {
    id: "trap-primer-paso",
    icon: "🩹",
    title: "Confundir el tratamiento definitivo con la primera medida",
    pattern: "Preguntan «actitud inicial» y las opciones incluyen tanto tratamiento definitivo como estabilización previa.",
    trap: "Se elige el tratamiento definitivo, olvidando ABC, analgesia, oxígeno o reposición.",
    howToAvoid: "Si pone «primera», piensa en estabilizar, no en resolver del todo.",
    example: "Neumotórax a tensión → primero descompresión, luego drenaje.",
    level: "alta",
  },
  {
    id: "trap-mejor-prueba",
    icon: "🧪",
    title: "Confundir screening, confirmación y gold standard",
    pattern: "Las opciones mezclan pruebas de cribado, confirmación y patrón oro.",
    trap: "Se marca la prueba más famosa aunque no sea la más apropiada en ese momento clínico.",
    howToAvoid: "Diferencia: sospecha inicial, prueba de confirmación, y patrón oro si lo preguntan expresamente.",
    example: "Asma: espirometría con reversibilidad para diagnóstico inicial; provocación bronquial si duda.",
    level: "alta",
  },
  {
    id: "trap-negacion-doble",
    icon: "🧠",
    title: "Doble negación y redacción retorcida",
    pattern: "Enunciados del tipo «no es infrecuente que no…» o «señale la falsa respecto a la opción correcta».",
    trap: "La carga cognitiva hace fallar incluso sabiendo el contenido.",
    howToAvoid: "Reformula mentalmente la frase en positivo antes de responder.",
    example: "«No es incorrecto afirmar que...» = «es correcto afirmar que...»",
    level: "alta",
  },
  {
    id: "trap-imagen-contexto",
    icon: "🖼️",
    title: "Imagen llamativa, dato clínico decisivo",
    pattern: "La imagen parece muy importante, pero el dato clínico del enunciado es el que decide la respuesta.",
    trap: "El aspirante se obsesiona con la imagen y olvida contexto, edad o evolución.",
    howToAvoid: "Usa la imagen como apoyo, no como sustituto del razonamiento clínico.",
    example: "ECG con cambios inespecíficos + dolor torácico típico e inestabilidad → manda la clínica.",
    level: "media",
  },
  {
    id: "trap-hsa-tac-normal",
    icon: "🧠",
    title: "TAC craneal normal NO descarta Hemorragia Subaracnoidea",
    pattern: "Cefalea súbita e intensa en trueno con TAC de cráneo inicial sin hallazgos patológicos.",
    trap: "Asumir que un TAC normal en las primeras horas descarta el sangrado subaracnoideo.",
    howToAvoid: "Ante clínica típica de HSA con TAC normal en las primeras 12-24h, la punción lumbar para buscar xantocromía es obligatoria.",
    example: "Paciente con la peor cefalea de su vida + TAC normal → Punción lumbar inmediata.",
    level: "alta",
  },
  {
    id: "trap-hiponatremia-velocidad",
    icon: "💧",
    title: "Hiponatremia: Corrección demasiado rápida",
    pattern: "Pregunta sobre el manejo urgente de hiponatremia grave sintomática.",
    trap: "Elegir una pauta de reposición excesivamente rápida sin controlar el límite de 8-10 mEq/L en 24 horas.",
    howToAvoid: "Recuerda que la corrección rápida en hiponatremia causa Mielinolisis Pontina Central (Síndrome de Desmielinización Osmótica).",
    example: "Tratar con Suero Salino Hipertónico al 3% para resolver síntomas agudos, pero limitando el ascenso <8 mEq/L/día.",
    level: "alta",
  },
  {
    id: "trap-embarazo-farmacos",
    icon: "🤰",
    title: "Contraindicación farmacológica estricta en el embarazo",
    pattern: "Tratamiento de infecciones o HTA en mujeres en edad fértil o gestantes.",
    trap: "Elegir fármacos de 1ª línea en población general que son teratogénicos (IECAs/ARAs, Quinolonas, Tetraciclinas).",
    howToAvoid: "En gestantes con HTA usa Labetalol/Nifedipino/Alfa-metildopa; en infecciones usa Betalactámicos o Fosfomicina.",
    example: "Cistitis en embarazada → Fosfomicina o Amoxicilina, NUNCA Ciprofloxacino.",
    level: "media",
  },
  {
    id: "trap-lactante-fiebre",
    icon: "👶",
    title: "Fiebre sin foco en lactante menor de 3 meses",
    pattern: "Lactante pequeño con fiebre alta sin focalidad clara a la exploración clínica.",
    trap: "Manejarlo como un cuadro vírico leve con antitérmicos y observación domiciliaria.",
    howToAvoid: "En <21-28 días o lactante de alto riesgo con fiebre sin foco, se requiere estudio completo de sepsis (hemocultivo, urinocultivo, PL y antibiótico IV empírico).",
    example: "Lactante de 18 días con 38.5ºC sin tos ni diarrea → Ingreso + analítica + PL + Ampicilina + Cefotaxima.",
    level: "alta",
  },
  {
    id: "trap-cocaina-betabloq",
    icon: "💊",
    title: "Uso de Betabloqueantes puros en intoxicación por Cocaína",
    pattern: "Paciente con dolor torácico o crisis hipertensiva tras consumo de sustancias (cocaína/anfetaminas).",
    trap: "Administrar Propranolol o Atenolol por la taquicardia/HTA.",
    howToAvoid: "El bloqueo beta puro deja el estímulo alfa sin oposición, empeorando el vasoespasmo coronario. Usa Benzodiacepinas ± Nitroglicerina.",
    example: "Varón de 25 años con dolor torácico y midriasis tras fiesta → Benzodiacepinas, NUNCA Propranolol.",
    level: "media",
  },
  {
    id: "trap-dato-llamativo",
    icon: "✨",
    title: "El dato llamativo que no cambia la conducta",
    pattern: "La pregunta introduce fiebre, comorbilidad o un antecedente espectacular, pero la clave está en el siguiente paso diagnóstico o terapéutico estándar.",
    trap: "El dato espectacular te distrae del protocolo estándar y te hace elegir una opción exótica.",
    howToAvoid: "Subraya edad, estabilidad hemodinámica, tiempo de evolución y la pregunta exacta antes de mirar opciones.",
    example: "Paciente con dolor torácico y muchos antecedentes espectaculares: si el ECG muestra elevación del ST, no te distraigas; reperfusión urgente.",
    level: "media",
  },
  {
    id: "trap-doble-negacion-nueva",
    icon: "🧠",
    title: "Negaciones y doble negación",
    pattern: "Enunciados con 'excepto', 'falsa', 'no es indicación' o 'todas salvo' castigan la lectura automática.",
    trap: "Se asume el sentido afirmativo por defecto y se marca la primera opción verdadera que leemos.",
    howToAvoid: "Marca visualmente la palabra negativa y reformula mentalmente: 'busco la opción incorrecta'.",
    example: "En vacunación, una contraindicación real pesa más que efectos adversos leves previos.",
    level: "básica",
  },
  {
    id: "trap-opciones-casi-verdaderas",
    icon: "⚖️",
    title: "Opciones casi verdaderas",
    pattern: "Dos respuestas suenan correctas, pero una incluye un absoluto: siempre, nunca, de elección en todos los casos.",
    trap: "El absoluto invalida la respuesta en medicina, donde casi todo tiene excepciones.",
    howToAvoid: "Desconfía de absolutos salvo criterios diagnósticos o tratamientos inequívocos.",
    example: "Antibiótico 'siempre' ante bronquitis aguda en sano suele ser distractor.",
    level: "media",
  },
  {
    id: "trap-tratamiento-antes-diag",
    icon: "🚑",
    title: "Tratamiento antes de diagnóstico de gravedad",
    pattern: "Te empujan a elegir una prueba sofisticada cuando primero hay que estabilizar o descartar urgencia vital.",
    trap: "La inercia de pedir pruebas retrasa la reanimación (ABCDE) o el manejo urgente.",
    howToAvoid: "Aplica ABCDE, constantes, embarazo, inmunosupresión y signos de alarma antes de pensar en pruebas raras.",
    example: "Cefalea con focalidad neurológica: neuroimagen urgente antes de punción lumbar.",
    level: "alta",
  },
  {
    id: "trap-fallo-tercio",
    icon: "🧮",
    title: "El 'fallo -1/3' del MIR (cálculo)",
    pattern: "Preguntas de cálculo de puntuación o de decisión clínica donde el enunciado lleva a contabilizar mal los fallos o a elegir un número 'redondo' que parece obvio.",
    trap: "Muchos calculan solo los aciertos o suman los blancos como puntos ganados. La clave es que los blancos son 0 y los fallos restan.",
    howToAvoid: "Aplica SIEMPRE la fórmula: neta = (aciertos × 3) − (fallos × 1). Ignora los blancos. Vuelve a leer la pregunta para confirmar cuántas preguntas valen y cuánto descuenta cada fallo.",
    example: "Un examen tiene 10 preguntas, cada una vale 3 puntos, resta 1 por fallo. Acerté 6, fallé 2 y dejé 2 en blanco. Puntuación neta = (6×3 - 2×1 = 16).",
    level: "media",
  },
  {
    id: "trap-mas-grave-sin-contexto",
    icon: "🚨",
    title: "Elegir la respuesta 'más grave' sin el contexto (razonamiento)",
    pattern: "En preguntas sobre diagnósticos, se ofrece siempre una opción muy grave (cáncer, sepsis) que suele ser la 'trampa' porque no encaja con el contexto del enunciado.",
    trap: "El término 'leucemia' genera alarma y lleva a elegirla como 'lo más grave'. Pero el perfil joven sin datos de blastos ni clínica constitucional dirige a una trombopenia aislada: PTI.",
    howToAvoid: "No elijas por gravedad percibida sino por adecuación al caso. Fíjate en la edad, los hallazgos y qué descarta más y menos cada opción. El MIR premia elegir el diagnóstico 'más probable', no el 'más grave'.",
    example: "Paciente joven con epistaxis recurrente y petequias. Opciones: leucemia aguda, púrpura trombocitopénica inmune, sepsis, enfermedad de von Willebrand, meningitis. Respuesta: PTI.",
    level: "media",
  },
  {
    id: "trap-intercambio-hematoquimica",
    icon: "🧪",
    title: "Intercambio Hematoquímica (memorística)",
    pattern: "Preguntas donde se intercambian dos valores clásicos (p. ej. sodio urinario alto/bajo, o ferritina/transferrina) y la opción 'invertida' es la trampa.",
    trap: "La etiqueta 'prerrenal' suena a 'pierde sodio' por su sonoridad, pero paradójicamente retiene sodio (Na urinario bajo). Se invierte la idea intuitiva.",
    howToAvoid: "Memoriza los pares opuestos como binomios: prerrenal = riñón conserva función → NaU bajo, UnU alta, sedimento benigno. NTA = pierde función → NaU alto (si es no oligúrica). Repásalos como listas contrapuestas.",
    example: "En la IRA prerrenal, el sodio urinario es < 20 mEq/L; en la necrosis tubular aguda es > 40. El examen plantea '¿en cuál el Na urinario es ALTO?' Respuesta: Necrosis tubular aguda.",
    level: "media",
  },
  {
    id: "trap-prefijo-temporal",
    icon: "⏱️",
    title: "Prefijo temporal 'en 24h / a los 3 días' (temporal)",
    pattern: "Preguntas donde el dato temporal decide la respuesta y el examinador inserta un plazo trampa para confundir (p. ej. trombólisis hasta 4,5h, angioplastia hasta 12h).",
    trap: "Es fácil confundir la ventana de la trombolisis (4,5h) con la de la angioplastia (12h). A las 10h la trombólisis ya NO está indicada, pero la angioplastia sí.",
    howToAvoid: "Convierte los plazos en 'ventanas' memorizadas con su acción: trombolítico ≤4,5h; angioplastia primaria ≤12h. Cuando la pregunta dé un tiempo, compáralo de inmediato con las ventanas, no lo 'calcules a ojo'.",
    example: "IAMCEST de 10 horas de evolución. ¿Está indicada la fibrinólisis intravenosa? Respuesta: No, ha pasado la ventana.",
    level: "alta",
  },
  {
    id: "trap-efecto-comorbilidades",
    icon: "🧓",
    title: "El efecto de las comorbilidades",
    pattern: "Preguntas de tratamiento donde aparece el paciente 'anciano', 'probando' o 'con insuficiencia renal' y se ofrece el fármaco estándar como opción, que en realidad está contraindicado.",
    trap: "La metformina es el 'especiero' del DM2 y parece inofensiva, pero en IRC G4 el riesgo de acidosis láctica obliga a usarla con cautela o retirarla.",
    howToAvoid: "Ante cualquier fármaco 'de primera línea' pregúntate por su excreción renal y hepatotoxicidad. Relaciona: metformina→acidosis láctica en IRC; IECA→hiperpotasemia; aminoglucósidos→nefrotoxicidad.",
    example: "DM2 mal controlado con metformina y enfermedad renal crónica estadio G4. ¿Qué fármaco debe retirarse o evitarse? Respuesta: Metformina.",
    level: "alta",
  },
  {
    id: "trap-localizacion-lateral",
    icon: "🦴",
    title: "Localización derecha vs izquierda (anatomía)",
    pattern: "Preguntas de anatomía/clínica donde se pide el lado correcto y el enunciado insinúa el contralateral, o al revés.",
    trap: "Existe confusión entre 'cubital produce garra' y 'mediano produce mano de predicador'. La sonoridad de 'húmero' empuja a 'axilar', que es fallo de plexo no específico.",
    howToAvoid: "Aprende cada nervio por su déficit motor+sensitivo característico como una 'ficha'. Cubital=garra/hormigueo 4º-5º dedo. Mediano=pinza/aprehensión pulgar. Radial=muñeca caída.",
    example: " ¿Qué vía se afecta en la parálisis del nervio que rodea el cuello del húmero para producir 'mano en garra'? Respuesta: Nervio cubital.",
    level: "media",
  },
  {
    id: "trap-frecuente-gana",
    icon: "📊",
    title: "'No sé, pero el más frecuente gana' (epidemiología)",
    pattern: "Preguntas estadísticas/epidemiológicas donde la causa más frecuente es la trampa por ser 'de manual' aunque clínicamente no encaje 100%.",
    trap: "En adultos la nefropatía membranosa es la más frecuente, pero el instinto recuerda 'cambios mínimos' por el niño. El examinador pregunta explícitamente 'en el adulto'.",
    howToAvoid: "Subraya mentalmente el parámetro poblacional (niño/adulto/anciano). Cambios mínimos→niño; membranosa→adulto. Asocia cada enfermedad a su rango de edad favorito.",
    example: "¿Cuál es la causa más frecuente de síndrome nefrótico en el adulto? Respuesta: Nefropatía membranosa.",
    level: "media",
  },
];
